### ISSUE TITLE
Cross build for 2.13

### ISSUE THREAD

**Issue by Daenyth** [outr/mailgun4s#10]
Opening this to track cross building for 2.13

**Comment by darkfrog26** [comment]
Unfortunately, I won't be able to tackle this immediately.  I ran into some problems with dependencies for YouI using 2.13 and need to wait until Circe fixes some Scala.js issues with their 2.13 release.

**Comment by Daenyth** [comment]
That's fine - I just wanted to track it. If you have ticket references handy for those upstream blockers, it would be good to list them here

**Comment by darkfrog26** [comment]
Released 1.0.13 with Scala 2.13 support
