### ISSUE TITLE
Changelog / git repo update?

### ISSUE THREAD

**Issue by Daenyth** [outr/mailgun4s#6]
I notice that 1.0.9 is released on maven central but the github repo here doesn't appear to be updated and there's no changelog. Is there any public post talking about what changed, or source to verify the jar against?

**Comment by Daenyth** [comment]
Nevermind, I thought it was a new upgrade because the README mentions 1.0.6, but it seems that there just hasn't been recent work

**Comment by darkfrog26** [comment]
I believe the only changes since 1.0.6 have been library dependency updates.  The library is surprisingly stable. :)  However, the README should be updated, so I'll leave this open until I get around to it or someone submits a PR. ;)

**Comment by Daenyth** [comment]
Are there notes now? Upgrading from 1.0.9->1.0.10 fails to compile for me, because the shutdown method was removed.

**Comment by darkfrog26** [comment]
You don't need a shutdown method anymore.
