### ISSUE TITLE
[Feature] Support region option when intializing Mailgun

### ISSUE THREAD

**Issue by maexrakete** [outr/mailgun4s#8]
Hey mate!

thanks for making this lib!

Mailgun currently supports setting up domains in specific regions, which means you have to set it up differently. For example the URL scheme for a EU domain is `https://api.eu.mailgun.net/v3/<DOMAIN>`. Currently the base domain is hardcoded, which means you can't configure it.

Would be great if one could give either a different base domain or add a region when initializing mailgun.

If you'd like I can try to implement it and make a pull request.

Regards

**Comment by darkfrog26** [comment]
I'd welcome a PR for that.
